Repository Justsvetoslavov/Object-oriented_programming_FMI_2021-2022, pull requests merged in 2022-04, with the labels that each got.

#1 Add Student solution
  .gitignore
  Sem. 06/Student/Student.cpp
  Sem. 06/Student/Student.h
Labels: enhancement

#2 Add files via upload
  Sem. 04/IntervalsTask/Interval.h
  Sem. 04/IntervalsTask/Intervals.cpp
  Sem. 04/IntervalsTask/Test.cpp
Labels: enhancement, help wanted

#3 Solution to : sem.05/practicum/Date
  Sem. 05/Practicum/Date.cpp
  Sem. 05/Practicum/Dates.h
  Sem. 05/Practicum/Main.cpp
Labels: enhancement, help wanted

#6 Sem.07/String.h
  Sem. 07/String/String.h
Labels: duplicate

#7 Added sem 7 complexNum reshenie
  Sem. 07/Practicum/ComplexNum.cpp
  Sem. 07/Practicum/ComplexNum.h
Labels: enhancement, good first issue

#5 Live coding session Yu Gi Oh code
  Sem. 06/Practicum/YuGiOh/Deck.cpp
  Sem. 06/Practicum/YuGiOh/Deck.h
  Sem. 06/Practicum/YuGiOh/Duelist.cpp
  Sem. 06/Practicum/YuGiOh/Duelist.h
  Sem. 06/Practicum/YuGiOh/MagicCard.cpp
  Sem. 06/Practicum/YuGiOh/MagicCard.h
  Sem. 06/Practicum/YuGiOh/MonsterCard.cpp
  Sem. 06/Practicum/YuGiOh/MonsterCard.h
Labels: enhancement, good first issue

#9 Nvector Solution by Nikolay Nikolaev
  Sem. 07/Practicum/Nvector/Cartesian.cpp
  Sem. 07/Practicum/Nvector/Cartesian.h
  Sem. 07/Practicum/Nvector/NVector.cpp
  Sem. 07/Practicum/Nvector/NVector.h
Labels: enhancement, help wanted, good first issue
